
echo "INSTALLATIN  SUPTV  IPK";
echo " SUPTV 4.1 IPK";
echo "FOR OPENPLI X ";
wget -O /tmp/enigma2-plugin-extensions-suptv_4.1_all.ipk http://uclagonteam.site/PLUGINS/enigma2-plugin-extensions-suptv_4.1_all.ipk
echo "Loading the plugin";
echo "Loading the plugin";
echo "Loading the plugin";
https://github.com/MARKETTV1/plugins/raw/refs/heads/main/enigma2-plugin-extensions-jk-multi-mod_2.1_all.ipk
echo "Please wait a moment";
wait
opkg install /tmp/*.ipk
init 4; sleep 4; init 3
